# Replace with NaN

In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_excel('Energy Indicators.xls')

In [28]:
df = df.iloc[16:243]
df

,Unnamed: 0,Unnamed: 1,Environmental Indicators: Energy,Unnamed: 3,Unnamed: 4,Unnamed: 5
16,NaN,Afghanistan,Afghanistan,321,10,78.6693
17,NaN,Albania,Albania,102,35,100
18,NaN,Algeria,Algeria,1959,51,0.55101
19,NaN,American Samoa,American Samoa,...,...,0.641026
20,NaN,Andorra,Andorra,9,121,88.6957
21,NaN,Angola,Angola,642,27,70.9091
22,NaN,Anguilla,Anguilla,2,136,0
23,NaN,Antigua and Barbuda,Antigua and Barbuda,8,84,0
24,NaN,Argentina,Argentina,3378,79,24.0645
25,NaN,Armenia,Armenia,143,48,28.2361
26,NaN,Aruba,Aruba,12,120,14.8707
27,NaN,Australia,Australia1,5386,231,11.8108
28,NaN,Austria,Austria,1391,164,72.4528
29,NaN,Azerbaijan,Azerbaijan,567,60,6.38434
30,NaN,Bahamas,Bahamas,45,118,0
31,NaN,Bahrain,Bahrain,574,425,0
32,NaN,Bangladesh,Bangladesh,1625,10,1.96633
33,NaN,Barbados,Barbados,19,69,0
34,NaN,Belarus,Belarus,1142,120,0.463389
35,NaN,Belgium,Belgium,2338,210,9.95974
36,NaN,Belize,Belize,13,39,64.69
37,NaN,Benin,Benin,170,16,0
38,NaN,Bermuda,Bermuda,6,88,0
39,NaN,Bhutan,Bhutan,63,83,100
40,NaN,Bolivia (Plurinational State of),Bolivia (Plurinational State of),336,32,31.4771
41,NaN,"Bonaire, Sint Eustatius and Saba","Bonaire, Sint Eustatius and Saba",5,213,0
42,NaN,Bosnia and Herzegovina,Bosnia and Herzegovina,266,70,41.4647
43,NaN,Botswana,Botswana,86,39,0.131406
44,NaN,Brazil,Brazil,12149,59,69.648
45,NaN,British Virgin Islands,British Virgin Islands,2,85,0
...,...,...,...,...,...,...
213,NaN,Switzerland,Switzerland17,1113,136,57.7455
214,NaN,Syrian Arab Republic,Syrian Arab Republic,542,28,11.5683
215,NaN,Tajikistan,Tajikistan,106,13,99.7429
216,NaN,Thailand,Thailand,5336,79,4.30519
217,NaN,The former Yugoslav Republic of Macedonia,The former Yugoslav Republic of Macedonia,117,56,26.1405
218,NaN,Timor-Leste,Timor-Leste,7,6,0
219,NaN,Togo,Togo,134,19,80.1802
220,NaN,Tonga,Tonga,3,28,0
221,NaN,Trinidad and Tobago,Trinidad and Tobago,824,611,0
222,NaN,Tunisia,Tunisia,430,39,3.49255
223,NaN,Turkey,Turkey,4897,64,28.5367
224,NaN,Turkmenistan,Turkmenistan,1102,210,0
225,NaN,Turks and Caicos Islands,Turks and Caicos Islands,3,85,0
226,NaN,Tuvalu,Tuvalu,...,...,0
227,NaN,Uganda,Uganda,452,12,68.0182
228,NaN,Ukraine,Ukraine18,4844,107,8.06731
229,NaN,United Arab Emirates,United Arab Emirates,2710,300,0
230,NaN,United Kingdom of Great Britain and Northern I...,United Kingdom of Great Britain and Northern I...,7920,124,10.6005
231,NaN,United Republic of Tanzania,United Republic of Tanzania,994,20,31.0728
232,NaN,United States of America,United States of America20,90838,286,11.571
233,NaN,United States Virgin Islands,United States Virgin Islands,...,...,0
234,NaN,Uruguay,Uruguay,196,58,71.605
235,NaN,Uzbekistan,Uzbekistan,1798,62,21.3284
236,NaN,Vanuatu,Vanuatu,3,10,14.7059
237,NaN,Venezuela (Bolivarian Republic of),Venezuela (Bolivarian Republic of),2871,95,67.8345
238,NaN,Viet Nam,Viet Nam,2554,28,45.3215
239,NaN,Wallis and Futuna Islands,Wallis and Futuna Islands,0,26,0
240,NaN,Yemen,Yemen,344,13,0
241,NaN,Zambia,Zambia,400,26,99.7147
242,NaN,Zimbabwe,Zimbabwe,480,32,52.5361

In [29]:
df.replace('...', np.nan, inplace = True)

In [30]:
df

,Unnamed: 0,Unnamed: 1,Environmental Indicators: Energy,Unnamed: 3,Unnamed: 4,Unnamed: 5
16,NaN,Afghanistan,Afghanistan,321.0,10.0,78.669280
17,NaN,Albania,Albania,102.0,35.0,100.000000
18,NaN,Algeria,Algeria,1959.0,51.0,0.551010
19,NaN,American Samoa,American Samoa,NaN,NaN,0.641026
20,NaN,Andorra,Andorra,9.0,121.0,88.695650
21,NaN,Angola,Angola,642.0,27.0,70.909090
22,NaN,Anguilla,Anguilla,2.0,136.0,0.000000
23,NaN,Antigua and Barbuda,Antigua and Barbuda,8.0,84.0,0.000000
24,NaN,Argentina,Argentina,3378.0,79.0,24.064520
25,NaN,Armenia,Armenia,143.0,48.0,28.236060
26,NaN,Aruba,Aruba,12.0,120.0,14.870690
27,NaN,Australia,Australia1,5386.0,231.0,11.810810
28,NaN,Austria,Austria,1391.0,164.0,72.452820
29,NaN,Azerbaijan,Azerbaijan,567.0,60.0,6.384345
30,NaN,Bahamas,Bahamas,45.0,118.0,0.000000
31,NaN,Bahrain,Bahrain,574.0,425.0,0.000000
32,NaN,Bangladesh,Bangladesh,1625.0,10.0,1.966329
33,NaN,Barbados,Barbados,19.0,69.0,0.000000
34,NaN,Belarus,Belarus,1142.0,120.0,0.463389
35,NaN,Belgium,Belgium,2338.0,210.0,9.959739
36,NaN,Belize,Belize,13.0,39.0,64.690030
37,NaN,Benin,Benin,170.0,16.0,0.000000
38,NaN,Bermuda,Bermuda,6.0,88.0,0.000000
39,NaN,Bhutan,Bhutan,63.0,83.0,100.000000
40,NaN,Bolivia (Plurinational State of),Bolivia (Plurinational State of),336.0,32.0,31.477120
41,NaN,"Bonaire, Sint Eustatius and Saba","Bonaire, Sint Eustatius and Saba",5.0,213.0,0.000000
42,NaN,Bosnia and Herzegovina,Bosnia and Herzegovina,266.0,70.0,41.464670
43,NaN,Botswana,Botswana,86.0,39.0,0.131406
44,NaN,Brazil,Brazil,12149.0,59.0,69.648030
45,NaN,British Virgin Islands,British Virgin Islands,2.0,85.0,0.000000
...,...,...,...,...,...,...
213,NaN,Switzerland,Switzerland17,1113.0,136.0,57.745480
214,NaN,Syrian Arab Republic,Syrian Arab Republic,542.0,28.0,11.568270
215,NaN,Tajikistan,Tajikistan,106.0,13.0,99.742920
216,NaN,Thailand,Thailand,5336.0,79.0,4.305189
217,NaN,The former Yugoslav Republic of Macedonia,The former Yugoslav Republic of Macedonia,117.0,56.0,26.140470
218,NaN,Timor-Leste,Timor-Leste,7.0,6.0,0.000000
219,NaN,Togo,Togo,134.0,19.0,80.180180
220,NaN,Tonga,Tonga,3.0,28.0,0.000000
221,NaN,Trinidad and Tobago,Trinidad and Tobago,824.0,611.0,0.000000
222,NaN,Tunisia,Tunisia,430.0,39.0,3.492547
223,NaN,Turkey,Turkey,4897.0,64.0,28.536690
224,NaN,Turkmenistan,Turkmenistan,1102.0,210.0,0.000000
225,NaN,Turks and Caicos Islands,Turks and Caicos Islands,3.0,85.0,0.000000
226,NaN,Tuvalu,Tuvalu,NaN,NaN,0.000000
227,NaN,Uganda,Uganda,452.0,12.0,68.018180
228,NaN,Ukraine,Ukraine18,4844.0,107.0,8.067312
229,NaN,United Arab Emirates,United Arab Emirates,2710.0,300.0,0.000000
230,NaN,United Kingdom of Great Britain and Northern I...,United Kingdom of Great Britain and Northern I...,7920.0,124.0,10.600470
231,NaN,United Republic of Tanzania,United Republic of Tanzania,994.0,20.0,31.072840
232,NaN,United States of America,United States of America20,90838.0,286.0,11.570980
233,NaN,United States Virgin Islands,United States Virgin Islands,NaN,NaN,0.000000
234,NaN,Uruguay,Uruguay,196.0,58.0,71.605040
235,NaN,Uzbekistan,Uzbekistan,1798.0,62.0,21.328410
236,NaN,Vanuatu,Vanuatu,3.0,10.0,14.705880
237,NaN,Venezuela (Bolivarian Republic of),Venezuela (Bolivarian Republic of),2871.0,95.0,67.834520
238,NaN,Viet Nam,Viet Nam,2554.0,28.0,45.321520
239,NaN,Wallis and Futuna Islands,Wallis and Futuna Islands,0.0,26.0,0.000000
240,NaN,Yemen,Yemen,344.0,13.0,0.000000
241,NaN,Zambia,Zambia,400.0,26.0,99.714670
242,NaN,Zimbabwe,Zimbabwe,480.0,32.0,52.536120